# 服务端口
server.port=8080
# 项目访问根路径
server.servlet.context-path=/

# JSP视图映射（webapp目录下所有jsp直接访问）
spring.mvc.view.prefix=/
spring.mvc.view.suffix=.jsp

# SQL Server数据库连接配置
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.url=jdbc:sqlserver://localhost:1433;DatabaseName=ShopDB;encrypt=true;trustServerCertificate=true;
spring.datasource.username=sa
spring.datasource.password=20060830

# 关闭缓存，开发实时刷新JSP
spring.web.resources.cache.period=0